### ISSUE TITLE
Is there a simple way to do this?

### ISSUE THREAD

**Issue by JuniperPhoton** [damyanp/SvgWin2D#3]
I have tried this:

> 1. Open the svg file as a XML file; 
> 2. Parse the xml document and find all of the svg element (e.g. path and line and more);
> 3. Get the data property (presented as 'd' in svg) and convert it to Windows.UI.XAML.Shapes.Path.Data property. 
> 4. Put paths within a ViewBox and add to visual tree to display it. 

It works and I think this is a way to solve the svg-to-xaml issue.

**Comment by damyanp** [comment]
Hi - if you want to extract SVG paths to XAML paths then this does seem like a reasonable approach.  This isn't really a goal of SvgWin2D, where the aim is to render entire SVG images using Win2D.

I can see some future version where it may be useful to extract bits of an SVG document to relevant Win2D objects (eg CanvasGeometry or ICanvasEffects)   Maybe some parts of SvgWin2D would be reusable by someone wanting to do SVG to XAML.

I'm going to close this since I don't think that there's any further action here.  Please feel free to reopen.
