### ISSUE TITLE
Possible issues when converting to C#

### ISSUE THREAD

**Issue by W0lfw00ds** [damyanp/SvgWin2D#4]
This is rather a question than an issue. I didn't find any other channel to ask this question.

I guess most of the Win2D users will be coding in C#. With a quick glance, I didn't notice anything that 'requires' this library to be coded in `C++/CLI`.  Is there anything that could be blocking the conversion to C#?

**Comment by damyanp** [comment]
This library isn't implemented using C++/CLI, it's implemented using C++/CX, which produces a WinRT component that can be consumed by C#.  The task of parsing an SVG file and render it with Win2D doesn't inherently require C++.  However, I chose C++ for this so that if a native app were to consume it then it wouldn't need to load the .NET runtime just to use it.

It's also worth calling out that Win2D is going to natively support SVG soon (see https://github.com/Microsoft/Win2D/issues/509).

**Comment by W0lfw00ds** [comment]
Thanks for correction! Native SVG support will be a great addition to the features. Basically thats the only thing I'm still missing! Nice.
